# Generated by Django 4.2.2 on 2023-07-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_withmoney_delete_ministatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=3000)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
