# Generated by Django 4.2.2 on 2023-07-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_newsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addamount',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withmoney',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
